[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "getcity"
version = "0.1.0"
description = "Find the nearest city to any geographical coordinates"
readme = "README.md"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
    "requests>=2.25.0",
    "appdirs>=1.4.4",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/getcity"
"Bug Tracker" = "https://github.com/yourusername/getcity/issues"

[project.scripts]
getcity = "nearest_city:main"